#include "SPP2AuxFiles.h"
#include "SPP2Globals.h"
#include "Network.h"
#include "OutputWin.h"

#include <QtCore>

/* File Name Declarations */
QString SPP2AuxFiles::ActFileName = "activity.config";
QString SPP2AuxFiles::SensFileName = "sensor.config";
QString SPP2AuxFiles::ConfigFileName = "ChipConfig.txt";
QString SPP2AuxFiles::NumElemsFileName = "numberOfElements.bin";
QString SPP2AuxFiles::NetStatsFileName = "NetworkStats.txt";

void SPP2AuxFiles::PrintFileBanner(QTextStream &outFile)
{
        outFile << "#*****************************************************************************************************" << "\n"
                        << "#*  Automatically generated by the NSI Neuro-Synthesis Tool (" <<  version << ") " << QDateTime::currentDateTime().toString() << "\n"
                        << "#*****************************************************************************************************" << "\n";
}

void SPP2AuxFiles::WriteNetStats()
{
        QFile txtFile(NetStatsFileName);
        if (!txtFile.open(QIODevice::WriteOnly))
        {
                OutputWin::error(0, "Cannot open file for writing: "
                             + txtFile.errorString());
                return;
        }
        QTextStream txtout(&txtFile);

        PrintFileBanner(txtout);

        txtout  << "Total groups: " << (int)Groups.size() << endl
                        << "Total elements: " << Network::TotalCells() << endl
                        << "Total simulated elements: " << Network::TotRegCells() << endl
                        << "Total sensor elements: " << Network::TotSensCells() << endl
                        << "Total connections: " << Network::TotalCxns() << endl
                        << "Average connections per simulated element: " << Network::AvgCxns() << endl
                        << "Average plastic connections per simulated element: " << Network::AvgPlast() << endl;

        txtout << endl << "Neuronal Group Synaptic Projections: " << endl;
        int cnt = 0;
        for (MacroLstIter it = MacroCxns.begin();
                                                it != MacroCxns.end(); ++it)
        {
                ++cnt;
                txtout << "( " << cnt << " ) " << QString::fromStdString((*it)->GetPreGrp()->GetName()) << " to "
                        << QString::fromStdString((*it)->GetPostGrp()->GetName()) << " with " << (*it)->GetNumCxns() << " connections " << endl;
        }
}

void SPP2AuxFiles::WriteNumElems()
{
        QFile File(NumElemsFileName);
        if (!File.open(QIODevice::WriteOnly))
        {
                OutputWin::error(0, "Cannot open file for writing: "
                             + File.errorString());
                return;
        }
        QDataStream out(&File);
        out.setVersion(QDataStream::Qt_4_1);
        out.setByteOrder(QDataStream::LittleEndian);/* ! LITTLE ENDIAN ! */

        for (int i = (NUM_CHIPS-1); i >= 0 ; --i)
        {
                out << uword(Chips[i]->OnCnt());
                out << uword(Chips[i]->SensCnt());
                out << uword(Chips[i]->GetWordBursts());
        }
}

void SPP2AuxFiles::WriteChipConfig()
{
        QFile txtFile(ConfigFileName);
        if (!txtFile.open(QIODevice::WriteOnly))
        {
                OutputWin::error(0, "Cannot open file for writing: "
                             + txtFile.errorString());
                return;
        }
        QTextStream txtout(&txtFile);

        PrintFileBanner(txtout);

        /* Write On and Sensor Groups First */
    for (int i = 0; i < (int)Chips.size(); ++i)
        {
                txtout << "CHIP " << Chips[i]->GetaID() << " ======================" << endl;
                txtout << "# Qty On-Chip Elements: " << Chips[i]->OnCnt() << endl;
                txtout << "# Qty Sensor Elements: "<< Chips[i]->SensCnt() << endl;
                txtout << "# Qty Connections serviced by this chip: " << QString::number(Chips[i]->GetNumInCxns()) << endl;
                txtout << "# Qty Plastic Connections serviced by this chip: " << QString::number(Chips[i]->GetNumPlastCxns()) << endl;

                txtout << "ON Chip Groups ------>" << endl;
                GrpLst OnGrps = Chips[i]->GetOnGrps();
                for (GrpLstIter it = OnGrps.begin(); it != OnGrps.end(); ++it)
                {
                        txtout << QString::fromStdString((*it)->GetName()) << endl;
                }

                txtout << "SENSOR Groups  ------>" << endl;
                GrpLst SensGrps = Chips[i]->GetSensGrps();
                for (GrpLstIter it = SensGrps.begin(); it != SensGrps.end(); ++it)
                {
                        txtout << QString::fromStdString((*it)->GetName()) << endl;
                }
                txtout << endl;
        }

        txtout << endl << endl;
        /* Write Off Groups Last */
        for (int i = 0; i < (int)Chips.size(); ++i)
        {
                txtout << "CHIP " << Chips[i]->GetaID() << " ======================" << endl;
                txtout << "OFF Chip Groups ------>" << endl;
                txtout << "# Qty Off-Chip Elements: " << Chips[i]->OffCnt() << endl;

                GrpLst OffGrps = Chips[i]->GetOffGrps();
                for (GrpLstIter it = OffGrps.begin(); it != OffGrps.end(); ++it)
                {
                        txtout << QString::fromStdString((*it)->GetName()) << endl;
                }
                txtout << endl;
        }
}

void SPP2AuxFiles::WriteActFile()
{
        QFile txtFile(ActFileName);
        if (!txtFile.open(QIODevice::WriteOnly))
        {
                OutputWin::error(0,  "Cannot open file for writing: "
                             + txtFile.errorString());
                return;
        }
        QTextStream txtout(&txtFile);

        PrintFileBanner(txtout);

        int cnt = 0, sz = 0;
        int NumTabs1 = 3;
        int NumTabs2 = 5;
        int TabConst = 6;
        QString TABS1(NumTabs1, '\t');
        QString TABS2(NumTabs2, '\t');
        QString GrpName;
        txtout << "#Group Name\t\tStart Byte Address\t\tEnd Byte Address" << endl;
        for (int i = 0; i < NUM_CHIPS; ++i)
        {
                GrpLst OnGrps = Chips[i]->GetOnGrps();
                for (GrpLstIter it = OnGrps.begin(); it != OnGrps.end(); ++it)
                {
                        sz = (*it)->GetSize();
                        GrpName = QString::fromStdString((*it)->GetName());
                        txtout << GrpName << QString((NumTabs1-(GrpName.size()/TabConst)),'\t')
                                   << cnt << TABS2 << (cnt+sz-1) << endl;

                        cnt += sz;
                }
        }
}

void SPP2AuxFiles::WriteSensFile()
{
        QFile txtFile(SensFileName);
        if (!txtFile.open(QIODevice::WriteOnly))
        {
                OutputWin::error(0, "Cannot open file for writing: "
                             + txtFile.errorString());
                return;
        }
        QTextStream txtout(&txtFile);

        PrintFileBanner(txtout);

        int cnt = 0, sz = 0;
        int NumTabs = 5;
        int TabConst = 6;
        QString TABS(NumTabs, '\t');
        QString GrpName;
        txtout << "#Sensor Group Name\t\tStart Byte Address\t\tEnd Byte Address" << endl;
        for (int i = 0; i < NUM_CHIPS; ++i)
        {
                GrpLst SensGrps = Chips[i]->GetSensGrps();
                for (GrpLstIter it = SensGrps.begin(); it != SensGrps.end(); ++it)
                {
                        sz = (*it)->GetSize();
                        GrpName = QString::fromStdString((*it)->GetName());
                        txtout << GrpName << QString((NumTabs-(GrpName.size()/TabConst)),'\t')
                                   << cnt << TABS << (cnt+sz-1) << endl;

                        cnt += sz;
                }
        }
}