/* (c) Copyright 1990-2016, The Rockefeller University *21115* */
/* $Id: newpltw.c 26 2013-10-31 17:48:00Z  $ */
/***********************************************************************
*                     ROCKS metafile plot library                      *
*                              newpltw()                               *
*                                                                      *
*  SYNOPSES:                                                           *
*     int newpltw(float xsiz, float ysiz, float xorg, float yorg,      *
*         const char *pentyp, const char *expcol, const char *chart,   *
*         int kout, unsigned int iwin, unsigned int fmode)             *
*                                                                      *
*     int newplt(float xsiz, float ysiz, float xorg, float yorg,       *
*         char *pentyp, char *expcol, char *chart, int kout)           *
*                                                                      *
*  DESCRIPTION:                                                        *
*     These functions begin a new graph and specify intialization      *
*     parameters.  One of them must be called for each graph, before   *
*     any other plotting calls (except factor() and the setxxx()       *
*     family).  This is a combined parallel and serial version.        *
*     On parallel computers, newpltw() should be called in parallel    *
*     from all processor nodes.  (The old routine newplt() is now a    *
*     wrapper for newpltw() that specifies window 0 and fmode 0.)      *
*                                                                      *
*  ARGUMENTS:                                                          *
*     xsiz    Width of plot (inches).                                  *
*     ysiz    Height of plot (inches).                                 *
*     xorg    X coord of plot origin--lower left corner.               *
*     yorg    Y coord of plot origin--lower left corner.               *
*     pentyp  Type of pen--may be implemented as different types       *
*             of lines on CRT displays (dashed, dotted, etc.)          *
*     expcol  Initial drawing color--defined in ctlkup.                *
*     chart   Type of paper for hard-copy plots.                       *
*     kout    This parameter controls the type of output for this      *
*             graph.  It may have bits SKP_META and/or SKP_XG set in   *
*             order to cause metafile or X graphics to be skipped      *
*             (assuming they are active globally).  DO_MVEXP may be    *
*             set to cause exposure of the graph on a movie device,    *
*             assuming this option is implemented.                     *
*     iwin    Number of window where graph should be drawn.            *
*     fmode   Frame mode options--see description in documentation of  *
*             frmdef() routine and definitions in plotdefs.h.  Summary *
*             for quick reference of bits allowed in newpltw() call:   *
*             FRM_BORD (0x01), frame has border; FRM_CLIP (0x02), clip *
*             at edges; FRM_DRAG (0x04), frame is draggable by user;   *
*             FRM_STOR (0x10), commands are stored for later use;      *
*             FRM_BMDR (0x20), frame is bookmarked each time drawn.    *
*                                                                      *
*  CURRENT PLOT POSITION ON RETURN:                                    *
*     (0,0) relative to specified plot origin.                         *
*                                                                      *
*  RETURN VALUES:                                                      *
*     0       Normal completion.                                       *
*     1       User pushed 'INTERRUPT' button to request interruption,  *
*             for example, to read input from a terminal.              *
*     2       User pushd 'QUIT' button to request termination of the   *
*             program.                                                 *
*             Note: Return code is broadcast to all nodes internally.  *
*     Other   Error conditions cause exit via mfckerr().               *
*                                                                      *
*  OTHER REQUIREMENTS:                                                 *
*     When this routine is used on a parallel computer, the makefile   *
*     must include the structure RKGSdef, defined in mfint.h, in the   *
*     list of structures for which conversion tables are needed.       *
*     (These are generated by running the NXDR2 utility at make time.) *
*                                                                      *
*     By tradition, the frame numbers written to mfdraw start at 0,    *
*     not 1.  This convention must be maintained or mfdraw version 8   *
*     will fail to read old metafiles.  This will be changed in MFD9.  *
************************************************************************
*  Rev, 10/04/90, JMS, GNR - Broken into separate function (ngraph)    *
*  Rev, 06/13/92, GNR, ROZ - Add metafile                              *
*  Rev, 08/10/92, ROZ - Add support for SUN and NOGDEV                 *
*  Rev, 07/15/93, GNR - Major rewrite.  Merge sergrph.  Use revised    *
*       mfhead, mfstart, fix cdtl comps, setup _RKG before using it    *
*  Rev, 09/16/94,  LC - ngraph() becomes newplt(), support variable    *
*                       window size.                                   *
*  Rev, 10/22/96, GNR - Use expcol argument to call pencol()           *
*  Rev, 11/25/96, GNR - Delete native NCUBE plotting support           *
*  Rev, 07/08/97, GNR - Communicate with mfdraw via socket, not pipe   *
*  V2A, 12/30/98, GNR - Make binary metafile (actually done in 2015)   *
*  Rev, 05/23/99, GNR - Use new swapping scheme                        *
*  Rev, 04/21/01, GNR - Add domvexp, later called kout                 *
*  Rev, 10/11/11, GNR - _NCG to _RKG, gmf.h now in mfint.h, etc.       *
*                       Calls setmf first time in case user didn't.    *
*                       Sets METF,SGX MFMode bits from setmf() fname,  *
*                       station args, no longer affected by BuffLen    *
*  Rev, 03/16/13, GNR - Fix bug in way color code was forced           *
*  Rev, 08/29/14, GNR - Add 'const' to pointer args                    *
*  Rev, 09/27/15, GNR - Update for current library spec                *
*  ==>, 08/27/16, GNR - Last date before committing to svn repository  *
***********************************************************************/

#include <stdlib.h>
#include <string.h>
#include "sysdef.h"
#include "mpitools.h"
#include "rksubs.h"
#include "mfint.h"
#include "mfio.h"
#include "plots.h"
#include "swap.h"
#ifdef PAR
#include "memshare.h"
#include "rkgnxdr.h"
extern long RKGTT[];          /* Structure conversion table */
#endif

/*=====================================================================*
*                               newpltw                                *
*=====================================================================*/

int newpltw(float xsiz, float ysiz, float xorg, float yorg,
      const char *pentyp, const char *expcol, const char *chart,
      int kout, unsigned int iwin, unsigned int fmode) {

   Frame *pcf;                /* Ptr to current frame */
   Win *pwin;                 /* Ptr to current window */
   float vvi[LVxx];           /* Coordinate transform */
   unsigned int ifrm;         /* Frame number */

   int rc = 0;                /* Return code */

#if defined(DEBUG) && DEBUG & MFDBG_NWPLT
   dbgprt("newplt() called");
#endif

   if (_RKG.MFFlags & MFF_MEnded) abexit(261);   /* No msg, unlikely */

/* Be sure the requested window has been opened.  Careful checks
*  are because mfcreate() may not have been called yet.  */

   if (!_RKG.pW0) {
      if (iwin > 0 || newwin() != 0) mfckerr(ERR_PWIN);
      }
   else {
      if (iwin > _RKG.nwallo ||
            !(_RKG.pW0[iwin].WinFlags & WFF_HasBuff))
         mfckerr(ERR_PWIN);
      }
   /* Effectively make this window current without calling chgwin() */
   _RKG.cwin = (ui16)iwin;
   pwin = _RKG.pcw = _RKG.pW0 + iwin;

/* If a frame is pending, now is the time for all nodes to flush
*  output and do an incoming synch before writing any stuff from
*  node 0 for a new frame.  Get button return code.  bpause() also
*  handles movies.  mfsynch() assures that soft buttons have been
*  returned from host window if one exists.  */

   if (pwin->WinFlags & WFF_FrmPend) {
#if defined(DEBUG) && DEBUG & MFDBG_NWPLT
      dbgprt("newpltw calling mfsynch because frame pending");
#endif
      mfsynch(KSYN_COMPLT|KSYN_FLUSH|KSYN_SYNC|KSYN_PWAIT);
      rc = bpause() & (BUT_INTX|BUT_QUIT);
#if defined(DEBUG) && DEBUG & MFDBG_NWPLT
      dbgprt(ssprintf(NULL, "newplt called bpause with msgbutt = %4m",
         &_RKG.msgbutt));
#endif
      pwin->WinFlags &=
         ~(WFF_COMPLT|WFF_DoMvExp|WFF_FrmPend|WFF_Atomic);
      if (rc) return rc;
      }

/* Be sure the window has a frame assigned.  If there already is one,
*  it can be reused for the new plot, otherwise assign a new one.
*  This info will be stored whether or not this plot will be drawn.  */

   vvi[VXX] = 1.0;
   vvi[VXY] = 0;
   vvi[VXC] = xorg;
   vvi[VYX] = 0;
   vvi[VYY] = 1.0;
   vvi[VYC] = yorg;
   ifrm = 0;
   pcf = pwin->pfr1;

   /* Remaining initialization done on all nodes */
   pwin->xsiz = xsiz, pwin->ysiz = ysiz;
   pwin->gobjid = 0;

/* Determine whether this specific frame will have output.  Until
*  the following broadcast, this can only be known on node 0.  */

#ifndef PARn
   /* Don't need to test rc here--already returned if !0 */
   pwin->MFActive = _RKG.s.MFMode & ~kout;   
   if (pwin->MFActive) {
      /* If this is the first time there will be output, now is
      *  the time to start up mfsr or mfdraw, open the metafile,
      *  and write the initial metafile header.  Otherwise, in-
      *  crement frame numbers for modes to be sent this time.  */
      if (_RKG.MFFlags & MFF_HdrSent) {         
         if (pwin->MFActive & METF) pwin->MFFrame += 1;
         if (pwin->MFActive & SGX)  pwin->XGFrame += 1;
         }
      else {
#if defined(DEBUG) && DEBUG & MFDBG_NWPLT
         dbgprt("newplt calling mfcreate--seems to be first plot");
#endif
         mfcreate();
         mfhead();
         _RKG.MFFlags |= MFF_HdrSent;
         } /* End starting mfsr/mfdraw and writing header */

      /* Write the '[' (Start Plot) record to buffer before
      *  the following broadcast allows comp nodes to proceed.
      *  mfstart() calls mfsynch(), so this record should be
      *  out to mfdraw on return.  */
#if defined(DEBUG) && DEBUG & MFDBG_NWPLT
      dbgprt("newpltw calling mfstart to start new plot record");
#endif
      mfstart(chart);

      /* Send parameters not in Start record.  This only needs to be
      *  done on Node 0 because saved in mfdraw for this window and
      *  frame.  Repeats frmdef() call above, now sends to file.  */
      frmdef(&ifrm, fmode|FRM_ROTN, xsiz, ysiz, vvi);
      penset(pentyp, expcol);

#ifdef PAR

/*$$$ TO HERE  Not clear whether the actual Bcast in old newplt
   is needed.  Not clear whether we can put the above frmdef
   inside mfstart so there are not two flushes at the start
   of the new window.
$$$ Somebody needs to set the bcodes in MFActive as in old
   newplt().  Also sets msgbutt.intxeq to 0.*/


      /* If multinode, flush buffer so start record arrives
      *  first at drawing package after broadcast below.  */
      if (IAmMulti) mfflush();
#endif
      } /* End if MFActive */
#endif /* !PARn */


/* Send button return code to all nodes.  This also serves as
*  synchronization point allowing comp nodes to start drawing.  */

#ifdef PAR
   if (_RKG.s.numnodes) {     /* Must be PAR at run time */
      mfsynch(KSYN_BCMB);
      } /* End if multinode */
#endif

   _RKG.MFFlags |= MFF_FirstBuff;

   return rc;
   } /* End newpltw() */

/*=====================================================================*
*                               newplt                                 *
*=====================================================================*/

int newplt(float xsiz, float ysiz, float xorg, float yorg,
         const char *pentyp, const char *expcol, const char *chart,
         int kout) {

   return newpltw(xsiz, ysiz, xorg, yorg, pentyp, expcol, chart,
      kout, 0, 0);

   } /* End newplt() */
