/* (c) Copyright 1992-2015, The Rockefeller University *21113* */
/**********************************************************************/
/*                             abend                                  */
/*                                                                    */
/*  "abend" displays the description that corresponds to an error     */
/*  number supplied by the user.  The program reads the errror table  */
/*  that resides in /usr/local/share/info (or wherever environment    */
/*  variable ABXERRTABLE points to) and prints the following:         */
/*  Error <error number> generated by <source file name>:             */
/*  <multilines description>                                          */
/*                                                                    */
/*  The format of the error file "errtab" is the following:           */
/*  First line    ->(column 0)<error number>(space)<program name>(\n) */
/*                  (comment: column 0 always starts with a digit)    */
/*  rest of lines -><description>                                     */
/*                  (comment: column 0 should never start with a      */
/*                   digit)                                           */
/*  Lines beginning with a '#' are comments                           */
/*                                                                    */
/*  Usage:  abend <error number>                                      */
/*                                                                    */
/* Version 1, 10/22/92, ROZ                                           */
/* Rev, 09/12/05, GNR - Move location of errtab file to crk source    */
/* Rev, 10/29/11, GNR - Add comment line recognition                  */
/* Rev, 06/04/15, GNR - Add default location and ABXERRTABLE          */
/**********************************************************************/

#include <stddef.h>
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>

#define ERRFILE_NAME  "/usr/local/share/info/errtab"
#define EFILENV_NAME  "ABXERRTABLE"
#define MAXFN  81

main(int argc, char *argv[]){

   FILE *fd;
   char *etpath;
   int errorno,itmp;
   char buffer[MAXFN], progname[MAXFN];

   if (argc != 2) {
      printf("(abend) Usage: abend <error number>\n");
      exit(999);
      }

   /* Get error number from line argument */
   errorno = atoi(argv[1]);

   /* Check for default errtab override */
   etpath = getenv(EFILENV_NAME);
   if (!etpath) etpath = ERRFILE_NAME;

   /* Open error table */
   if ((fd = fopen(etpath,"r")) == NULL) {
     fprintf(stderr,"Open %s failed \n",etpath);
     exit(1);
     }

   /* Find error number in error table */
   clearerr(fd);
   rewind(fd);
   while(!feof(fd)) {
      fgets(buffer,80,fd);
      if (buffer[0] == '#') continue;
      if (isdigit(buffer[0]) && (errorno == atoi(buffer))) {

         /* Print error description */
         sscanf(buffer,"%d %s",&itmp,progname);
         printf("Error %d generated by %s:\n",itmp,progname);
         while(!feof(fd)) {
            fgets(buffer,80,fd);
            if (isdigit(buffer[0]) || buffer[0] == '#' ||
               feof(fd)) { exit(0); }
            printf("%s",buffer);
            }
         }
      }
   printf("Undocumented error number!!!\n",errorno);
   close(fd);
   }
