           TITLE "UDEV - GENERATE UNIFORM AND NORMAL RANDOM NUMBERS"
; (c) Copyright 1989-2008, The Rockefeller University *11611*
; $Id: udev.s 61 2017-01-16 19:26:44Z  $
;**********************************************************************
;                                                                     *
;     ROCKS CRYSTALLOGRAPHIC COMPUTING SYSTEM - C IMPLEMENTATION      *
;                                                                     *
;     This program contains udev, a routine to generate a single      *
;     uniformly distributed random number, and ndev, a routine to     *
;     generate a single normally distributed random number.  This     *
;     is the PCLINUX version.                                         *
;                                                                     *
;**********************************************************************
;                                                                     *
;     Algorithm:  Uniformly distributed pseudo-random integers        *
;        are generated by ir = seed*(7**5) MODULO (2**31-1).          *
;        The first eight bits of each are used to select from a       *
;        look-up table an interval of width 0.125 in the range        *
;        0.0-3.0 with appropriate frequency.  The remaining bits      *
;        specify the location within the chosen intervala and         *
;        the sign.  The resulting value is multiplied by 'sigma'      *
;        and finally 'mean' is added.  The result is a piecewise      *
;        rectangular approximation to the true Gaussian distribu-     *
;        tion, good enough for most purposes.  See Knuth, Vol. 2.     *
;                                                                     *
;**********************************************************************
;
;  V1A, 07/24/89, G. N. REEKE
;  ==>, 08/11/99, GNR - Last date before committing to svn repository   
;
	.file	"udev.s"
	.version	"01.01"
.text
	.align 4
.globl udev
	.type	 udev,@function

;---------------------------------------------------------------------*
;                                                                     *
;                        long udev(long *seed)                        *
;                                                                     *
;---------------------------------------------------------------------*

udev:
	pushl %ebp
	movl %esp,%ebp
	subl $12,%esp
	pushl %ebx

;   long s0m = (unsigned long)(*seed & 0xffffL) * m;

	movl 8(%ebp),%edx
	movl (%edx),%eax
	andl $65535,%eax
	movl %eax,%edx
	sall $2,%edx
	addl %eax,%edx
	movl %edx,%ecx
	sall $4,%ecx
	subl %edx,%ecx
	movl %ecx,%edx
	sall $5,%edx
	addl %eax,%edx
	leal 0(,%edx,8),%eax
	movl %eax,%ebx
	subl %edx,%ebx
	movl %ebx,-4(%ebp)
	movl -4(%ebp),%ebx
	movzwl %bx,%ebx
	movl %ebx,-8(%ebp)
	movl 8(%ebp),%edx

;   unsigned long smhi = ((unsigned long)(*seed)>>16)*m +
;      ((unsigned long)s0m>>16);

	movl (%edx),%eax
	shrl $16,%eax
	movl %eax,%edx
	sall $2,%edx
	addl %eax,%edx
	movl %edx,%ecx
	sall $4,%ecx
	subl %edx,%ecx
	movl %ecx,%edx
	sall $5,%edx
	addl %eax,%edx
	leal 0(,%edx,8),%eax
	subl %edx,%eax
	movl -4(%ebp),%edx
	shrl $16,%edx
	leal (%edx,%eax),%ebx

;   long smlo = s0m & 0xffffL;
;   smlo += ((smhi & 0x7fffL) << 16) + (smhi >> 15);

	movl %ebx,-12(%ebp)
	movl -12(%ebp),%eax
	andl $32767,%eax
	movl %eax,%edx
	sall $16,%edx
	movl -12(%ebp),%eax
	shrl $15,%eax
	addl %eax,%edx
	addl %edx,-8(%ebp)

;   smlo += (smlo < 0);

	movl -8(%ebp),%eax
	shrl $31,%eax
	addl -8(%ebp),%eax

;   smlo &= 0x7fffffff;

	movl %eax,-8(%ebp)
	andb $127,-5(%ebp)

;   return (*seed = smlo);        /* Return result */

	movl 8(%ebp),%eax
	movl -8(%ebp),%edx
	movl %edx,(%eax)
	movl %edx,%eax
	jmp .L1
	.p2align 4,,7
.L1:
	movl -16(%ebp),%ebx
	leave
	ret
.Lfe1:
	.size	 udev,.Lfe1-udev
