// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef mfdrawUI_h
#define mfdrawUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "mfdrawsockserver.h"
#include <FL/Fl_Group.H>
#include "mfdraw.h"
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_File_Chooser.H>
extern string mf_filename;
#include <FL/fl_ask.H>
#include <FL/Fl_Button.H>
extern bool fastforward, fastprevious;
extern int MINFRAMEVIEWTIMEPREV;
#include <sys/time.h>
extern bool fastforward; extern int MINFRAMEVIEWTIMENEXT;
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Value_Slider.H>
#include <math.h>
#include <FL/Fl_Adjuster.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Input.H>

class FrameViewUI {
public:
  FrameViewUI();
  Fl_Double_Window *mainWindow;
private:
  void cb_mainWindow_i(Fl_Double_Window*, void*);
  static void cb_mainWindow(Fl_Double_Window*, void*);
public:
  Fl_Group *Controls;
  Fl_Menu_Button *MenuFilebutton;
  static Fl_Menu_Item menu_MenuFilebutton[];
private:
  void cb_Open_i(Fl_Menu_*, void*);
  static void cb_Open(Fl_Menu_*, void*);
  void cb_Settings_i(Fl_Menu_*, void*);
  static void cb_Settings(Fl_Menu_*, void*);
  void cb_About_i(Fl_Menu_*, void*);
  static void cb_About(Fl_Menu_*, void*);
  void cb_Exit_i(Fl_Menu_*, void*);
  static void cb_Exit(Fl_Menu_*, void*);
public:
  Fl_Button *Netbutton;
private:
  void cb_Netbutton_i(Fl_Button*, void*);
  static void cb_Netbutton(Fl_Button*, void*);
  void cb__i(Fl_Button*, void*);
  static void cb_(Fl_Button*, void*);
  void cb_1_i(Fl_Button*, void*);
  static void cb_1(Fl_Button*, void*);
public:
  Fl_Button *prevfrm;
private:
  void cb_prevfrm_i(Fl_Button*, void*);
  static void cb_prevfrm(Fl_Button*, void*);
public:
  Fl_Button *nxtfrm;
private:
  void cb_nxtfrm_i(Fl_Button*, void*);
  static void cb_nxtfrm(Fl_Button*, void*);
  void cb_2_i(Fl_Button*, void*);
  static void cb_2(Fl_Button*, void*);
  void cb_3_i(Fl_Button*, void*);
  static void cb_3(Fl_Button*, void*);
  void cb_Origin_i(Fl_Light_Button*, void*);
  static void cb_Origin(Fl_Light_Button*, void*);
public:
  Fl_Value_Slider *zoom;
private:
  void cb_zoom_i(Fl_Value_Slider*, void*);
  static void cb_zoom(Fl_Value_Slider*, void*);
public:
  Fl_Adjuster *zoomadjuster;
private:
  void cb_zoomadjuster_i(Fl_Adjuster*, void*);
  static void cb_zoomadjuster(Fl_Adjuster*, void*);
public:
  Fl_Box *zoomdisplay;
private:
  void cb_zoomdisplay_i(Fl_Box*, void*);
  static void cb_zoomdisplay(Fl_Box*, void*);
  void cb_4_i(Fl_Button*, void*);
  static void cb_4(Fl_Button*, void*);
  void cb_5_i(Fl_Button*, void*);
  static void cb_5(Fl_Button*, void*);
  void cb_GoTo_i(Fl_Value_Input*, void*);
  static void cb_GoTo(Fl_Value_Input*, void*);
  void cb_6_i(Fl_Button*, void*);
  static void cb_6(Fl_Button*, void*);
public:
  Fl_Group *MainView;
  FrameView *glView;
  Fl_Double_Window *Netdialog;
private:
  void cb_Netdialog_i(Fl_Double_Window*, void*);
  static void cb_Netdialog(Fl_Double_Window*, void*);
  void cb_Step_i(Fl_Button*, void*);
  static void cb_Step(Fl_Button*, void*);
  void cb_Movie_i(Fl_Button*, void*);
  static void cb_Movie(Fl_Button*, void*);
  void cb_Interrupt_i(Fl_Button*, void*);
  static void cb_Interrupt(Fl_Button*, void*);
  void cb_Quit_i(Fl_Button*, void*);
  static void cb_Quit(Fl_Button*, void*);
public:
  Fl_Double_Window *Settings;
  Fl_Value_Input *minframeviewtimeprev;
  Fl_Value_Input *minframeviewtimenext;
  Fl_Value_Input *xposwindow;
  Fl_Value_Input *yposwindow;
  Fl_Value_Input *mainwindowwidthsize;
private:
  void cb_CANCEL_i(Fl_Button*, void*);
  static void cb_CANCEL(Fl_Button*, void*);
  void cb_SAVE_i(Fl_Button*, void*);
  static void cb_SAVE(Fl_Button*, void*);
  void cb_OK_i(Fl_Button*, void*);
  static void cb_OK(Fl_Button*, void*);
public:
  Fl_Double_Window *ExitContinue;
private:
  void cb_CONTINUE_i(Fl_Button*, void*);
  static void cb_CONTINUE(Fl_Button*, void*);
  void cb_EXIT_i(Fl_Button*, void*);
  static void cb_EXIT(Fl_Button*, void*);
public:
  void show(int argc, char **argv);
};
#endif
