/* (c) Copyright 2010, Neurosciences Research Foundation, Inc. */
/* $Id: utvdef.h 44 2011-03-04 22:36:14Z  $ */
/***********************************************************************
*                             CNS Program                              *
*                         UTVDEF Header File                           *
*                                                                      *
*  This parameter block contains camera parameters that can be passed  *
*  to a user program providing images to CNS.  It is a subset of the   *
*  information in the TVDEF header that is sanitized to remove types   *
*  and defs that the user program need not have access to.  There is   *
*  space for the user code to store a pointer (maybe to an RFDEF)      *
*  where state information can be stored between calls.                *
*                                                                      *
*  Additionally, a UPREPR parameter block is defined that will be      *
*  passed to user-written image preprocessors for similar purposes.    *
************************************************************************                                                                      *
*  V8F, 02/13/10, GNR - New header file                                *
*  ==>, 02/13/10, GNR - Last mod before committing to svn repository   *
*  Rev, 05/12/10, GNR - Add UPREPR                                     *
*  Rev, 06/01/10, GNR - Add utvinfo                                    *
***********************************************************************/

typedef byte PIXEL;           /* Pixel type */
#define MAXGRAY     256       /* Highest gray level in an image + 1 */
#define NUTVINFO      4       /* Bytes of info for SAVE UTVINFO */

/* Define a camera (could be still or TV) */

struct UTVDEF {
   void  *ptvsrc;             /* Ptr to BBD or VVTV source or
                              *  user data if this is UPGM camera */
   ui16  tvix,tviy;           /* Size of input image BEFORE avg */
   ui16  tvx, tvy;            /* Size of sampled image AFTER avg */
   ui16  tvxo;                /* x offset of sample from left edge of
                              *  image in pixels, BEFORE averaging */
   ui16  tvyo;                /* y offset of sample from top edge of
                              *  image in pixels, BEFORE averaging */
   ui16  isn;                 /* Stimulus number returned by camera */
   ui16  ign;                 /* Group number */
   ui16  tvsflgs;             /* System flags */
/* Flags that may be stored in tvsflgs: */
#define TV_ON        0x0001      /* This TV is used or plotted */
#define TV_ONDIR     0x0002      /* This TV is used directly */
#define TV_ONPP      0x0004      /* This TV is used via preprocessor */
/* TV_VVTV,TV_BBD,TV_UPGM must match EVTVTV,EVTBTV,EVTUTV, bzw. */
#define TV_VVTV      0x0010      /* Use VVTV interface */
#define TV_BBD       0x0020      /* Use BBD interface */
#define TV_UPGM      0x0040      /* Use UPGM interface */
/* Combos of frequency and interface for faster run-time tests.
*  N.B.  These are generated by shifts in d3tchk and must not
*  be redefined without modifying that code accordingly.  */
#define TV_SerVVTV   0x0080      /* Series freq VVTV, etc. */
#define TV_SerBBD    0x0100
#define TV_SerUPGM   0x0200
#define TV_EvtVVTV   0x0400
#define TV_EvtBBD    0x0800
#define TV_EvtUPGM   0x1000
#define TV_TriVVTV   0x2000
#define TV_TriBBD    0x4000
#define TV_TriUPGM   0x8000
   short iadapt;              /* Adaptiveness value (S8) */
   byte  utvinfo[NUTVINFO];   /* Arbitrary data for SIMDATA */
#define UTVInf_INST       0      /* Instance of the stimulus */
#define UTVInf_ELEV       1      /* Elevation of the stimulus */
#define UTVInf_AZIM       2      /* Azimuth of the stimulus */
#define UTVInf_LGHT       3      /* Lighting condition */
   byte  icam;                /* Camera number (from 1) */
   byte  islot;               /* Slot number (for multicam cards) */
   byte  tvsa;                /* Spatial averaging factor */
   byte  tvta;                /* Temporal averaging factor */
   byte  tvuflgs;             /* User flags */
/* Flags that may be stored in tvuflgs: */
#define TV_UFL1          0x01    /* '1' Opt--User-defined code 1 */
#define TV_UFL2          0x02    /* '2' Opt--User-defined code 2 */
#define TV_PLOT          0x04    /* 'P' Opt--Plot image supers */
#define TV_PISG          0x08    /* 'I' Opt--Plot isn,ign */
#define TV_OTITL         0x10    /* 'O' Opt--Omit image title */
#define TV_RESCL         0x20    /* 'R' Opt--Rescale gray levels */
#define TV_BYPR          0x40    /* 'B' Opt--Bypass reset */
   byte  tvkcol;              /* Color mode */
/* Flags that may be stored in tvkcol (these are the same as the
*  corresponding BBDCol options, but are given different names
*  to allow future differentiation of these options):  */
#define UTVCol_GS        0x00    /* Gray-scale image (8 bit) */
#define UTVCol_C8        0x01    /*  8-bit color (2-3-3 BGR) */
#define UTVCol_C16       0x02    /* 16-bit color (5-5-5 RGB) */
#define UTVCol_C24       0x03    /* 24-bit color (8-8-8 RGB) */
   byte  tvkfreq;             /* Access frequency */
/* Flags that may be stored in tvkfreq (these are the same as the
*  corresponding BBDCFr options, but are given different names
*  to allow future differentiation of these options):  */
#define UTVCFr_TRIAL     0x01    /* Grab on every trial */
#define UTVCFr_EVENT     0x02    /* Grab on designated event */
#define UTVCFr_SERIES    0x03    /* Grab on new series */
   } ;

/* Define information for user-written image preprocessor */

struct UPREPR {
   struct KERNEL *pipk;       /* Ptr to kernel block */
   void *pupd;                /* Ptr to arbitrary user data */
   /* Derived constants used repeatedly in d3imgt() */
   ui32  tvx3;                /* Byte length of full input row */
   ui32  nipx3;               /* Byte length of used input row */
   ui32  oin0;                /* Offset to first input pixel */
   ui32  lrowskip;            /* Length of end-of-row input skip */
   ui16  nipx,nipy;           /* X,Y dimensions of output array */
   ui16  oipx,oipy;           /* X,Y offsets of output in input */
   ui16  nker;                /* Number of kernels */
   byte  ipuflgs;             /* User flags */
/* Flags that may be stored in ipuflgs: */
#define PP_PLOT          0x01    /* 'B' Opt--Draw image supers */
#define PP_OTITL         0x02    /* 'O' Opt--Omit image title */
#define PP_2SYMM         0x04    /* '2' Opt--Apply twofold symmetry */
   byte  ipkcol;              /* Color mode--values from enum
                              *  ColorMode defined in d3global.h */
   } ;

/* Prototype routines that use UTVDEF struct */
/* Values for kcall argument: */
enum tvinit_kcall {
   TV_INIT = 0,               /* UPGM initialization call */
   TV_RESET,                  /* UPGM reset call */
   TV_RESTART,                /* UPGM restart (new UDATA) call */
   TV_CLOSE };                /* UPGM close files call */
int tvinitfn(struct UTVDEF *putv, char *camnm,
   const char *ufile, const char *udata, enum tvinit_kcall kcall);
int tvgrabfn(struct UTVDEF *putv, PIXEL *pimage);
/* Prototype routine that uses UPREPR struct */
int preprfn(struct UPREPR *pupr, PIXEL *pin, PIXEL *pout);
