// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "mfdrawUI.h"

void FrameViewUI::cb_mainWindow_i(Fl_Double_Window*, void*) {
  if (Fl::event_key() == FL_Escape)
      exit(0);
	if (skey == false)
	   //the s key was not pressed so we must be getting
      // a close window / close app command
      exit(0);

   if (Fl::event_key() == 's' || Fl::event_key() == 'S') {
      static int toggle = 0;
      static int px;
      static int py;
      static int pw;
      static int ph;
      static int phglview;
      if (toggle == 0) {
         px = mainWindow->x();
         py = mainWindow->y();
         pw = mainWindow->w();
         ph = mainWindow->h();
         phglview = glView->h();
         mainWindow->border(0);
         mainWindow->fullscreen();
         //cout<<"in mainWindow Callback: full screen called"<<endl;
         //ptrcontrols->hide();
         glView->resize(0,0,mainWindow->w(),mainWindow->h());
         mainWindow->redraw();
         toggle = 1;
         }
      else {
         mainWindow->fullscreen_off(px, py, pw, ph);
         //cout<<"in mainWindow Callback: full screen_off called"<<endl;
         mainWindow->border(1);
         glView->resize(0,25,pw,phglview);
         //ptrcontrols->show();
         mainWindow->redraw();
         toggle = 0;
         }
   	return;
   	} // End event key s
   exit(0);
}
void FrameViewUI::cb_mainWindow(Fl_Double_Window* o, void* v) {
  ((FrameViewUI*)(o->user_data()))->cb_mainWindow_i(o,v);
}

void FrameViewUI::cb_Open_i(Fl_Menu_* o, void*) {
  if (runmode == SOCKMODE) {
      fl_alert("You are in cns socket mode. you cannot use "
         "the File control to input data.");
      o->deactivate();
      mf_filename = "cns socket mode ";
      return;
      }
   static bool metaopened = false;

/* GNR 5/5/14 Delete when code works after "cancel"
   static char filename[120];

   sprintf(filename, "%s", fl_file_chooser("Pick a meta data file.",
        "Meta Command Files (*.mf)", "", 0));
   string s(filename);
   if (s == "(null)")
      return;
*/
   char *tfn = fl_file_chooser("Pick a meta data file.",
      "Meta Command Files (*.mf)", "", 0);
   if (!tfn) return;
   mf_filename = tfn;

   if (metaopened == false)
      metaopened = true;
   else {
      fl_alert("cannot open metafile if metafile is already open");
      return;
      }

   //clear out any data and initialize prior to loading new data
   deletedata();
   createdata(tfn);
   buildframetracker();
   LISTOFCOMMANDS::iterator frit;
   frit = frametracker[atframe]; //frame is pointed to by the iterators
      // in frametracker[n]
   glView->left = ((Newframe*)(*frit))->left;
   glView->right = ((Newframe*)(*frit))->right;
   glView->bottom = ((Newframe*)(*frit))->bottom;
   glView->top = ((Newframe*)(*frit))->top;
   glView->invalidate();
   glView->redraw();
   glFlush();
   glFinish(); //force completion of draw prior to next frame -
      // only at file load
   mainWindow->label("");
   static char firstlabel[120];
   sprintf(firstlabel, "%s", header2.c_str());
   mainWindow->label(firstlabel);

   zoom->value(1);
   glView->init();
   runmode = FILEMODE;

   //------ used to automatically load frames 1 through N
   // while displaying the first frame see also createdata()
   bool initialload = true;

   while (moreframes && initialload) {

      if (lastframe == MAXNUMFRAMES-2)
         initialload = false;
      createdata(tfn);
      buildframetracker();

      Fl::check(); //++moved from createdata 1/25/08
      };
}
void FrameViewUI::cb_Open(Fl_Menu_* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_Open_i(o,v);
}

void FrameViewUI::cb_Settings_i(Fl_Menu_*, void*) {
  ptrsettings->show();
}
void FrameViewUI::cb_Settings(Fl_Menu_* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_Settings_i(o,v);
}

void FrameViewUI::cb_About_i(Fl_Menu_*, void*) {
  const GLubyte *mesaversion = glGetString(GL_VERSION);
      const GLubyte *mesarenderer = glGetString(GL_RENDERER);
      int fltkmajorv = FL_MAJOR_VERSION;
      int fltkminorv = FL_MINOR_VERSION;
      int fltkpatch  = FL_PATCH_VERSION;

      char fltkversion[100];
      sprintf(fltkversion, "fltk version = %d.%d.%d",
         fltkmajorv, fltkminorv, fltkpatch);

      char shortcuts[300];
      sprintf(shortcuts, "Shortcut keys (upper or lower case allowed):"
         "\nA about info\nB toggle background\nF file dialog"
         "\nH home\nM toggle movie and step"
         "\nN socket mode dialog\nO set origin with cursor"
         "\nctl-Q or alt-F4 quit\nup/down arrows for precision zoom"
         "\nleft/right arrows for frame back or forward");
      fl_message("%s\n%s\n%s\n%s\n%s\t%s\n%s\n%s",
         mfdrawversion, header1.c_str(), header2.c_str(),
         header3.c_str(), mesaversion, mesarenderer, fltkversion,
         shortcuts);
}
void FrameViewUI::cb_About(Fl_Menu_* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_About_i(o,v);
}

void FrameViewUI::cb_Exit_i(Fl_Menu_*, void*) {
  if (runmode == SOCKMODE) {
         closeconnection();
         exit(0);
         }
      exit(0);
}
void FrameViewUI::cb_Exit(Fl_Menu_* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_Exit_i(o,v);
}

Fl_Menu_Item FrameViewUI::menu_MenuFilebutton[] = {
 {"&Open file", 0,  (Fl_Callback*)FrameViewUI::cb_Open, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {"&Settings", 0,  (Fl_Callback*)FrameViewUI::cb_Settings, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {"&About", 0,  (Fl_Callback*)FrameViewUI::cb_About, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {"&Exit", 0,  (Fl_Callback*)FrameViewUI::cb_Exit, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {0,0,0,0,0,0,0,0,0}
};

void FrameViewUI::cb_Netbutton_i(Fl_Button* o, void*) {
  if (runmode == SOCKMODE) {
         Netdialog->show(); }
      else {
         fl_alert("You are in file mode not cns socket mode. "
            "Use the file menu or exit.");
         o->deactivate(); };
}
void FrameViewUI::cb_Netbutton(Fl_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_Netbutton_i(o,v);
}

void FrameViewUI::cb__i(Fl_Button*, void*) {
  if (sListofCommands.empty())
         return;

      fastforward  = false;
      fastprevious = false;

      atframe = 1;
      drawFrameCommon(glView, 0, 1);
}
void FrameViewUI::cb_(Fl_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb__i(o,v);
}

void FrameViewUI::cb_1_i(Fl_Button*, void*) {
  fastprevious_cb(glView);
}
void FrameViewUI::cb_1(Fl_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_1_i(o,v);
}

void FrameViewUI::cb_prevfrm_i(Fl_Button*, void*) {
  fastforward = false;
      fastprevious = false;
      prevframe_cb(glView);
}
void FrameViewUI::cb_prevfrm(Fl_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_prevfrm_i(o,v);
}

void FrameViewUI::cb_2_i(Fl_Button*, void*) {
  if (sListofCommands.empty())
         return;

      fastforward  = false;
      fastprevious = false;
      drawFrameCommon(glView, 0, 1);
}
void FrameViewUI::cb_2(Fl_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_2_i(o,v);
}

void FrameViewUI::cb_nxtfrm_i(Fl_Button*, void*) {
  fastforward = false;
      fastprevious = false;
      nextframe_cb(glView);
}
void FrameViewUI::cb_nxtfrm(Fl_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_nxtfrm_i(o,v);
}

void FrameViewUI::cb_3_i(Fl_Button*, void*) {
  fastforward_cb(glView);
}
void FrameViewUI::cb_3(Fl_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_3_i(o,v);
}

void FrameViewUI::cb_4_i(Fl_Button*, void*) {
  if (sListofCommands.empty())
         return;

      fastforward  = false;
      fastprevious = false;

      atframe = lastframe;
      drawFrameCommon(glView, 0, 1);
}
void FrameViewUI::cb_4(Fl_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_4_i(o,v);
}

void FrameViewUI::cb_5_i(Fl_Button*, void*) {
  glView->home();
}
void FrameViewUI::cb_5(Fl_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_5_i(o,v);
}

#include <FL/Fl_Image.H>
static unsigned char idata_fit[] =
{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static Fl_RGB_Image image_fit(idata_fit, 22, 21, 3, 0);

void FrameViewUI::cb_6_i(Fl_Button*, void*) {
  glView->bkgrndwhite[atframe] = !glView->bkgrndwhite[atframe];
      glView->redraw();
}
void FrameViewUI::cb_6(Fl_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_6_i(o,v);
}

static unsigned char idata_background4[] =
{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,0,0,0,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,0,0,0,0,0,0,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,255,255,255,255,255,255,255,255,255,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,255,255,255,255,255,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,255,255,255,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static Fl_RGB_Image image_background4(idata_background4, 21, 21, 3, 0);

void FrameViewUI::cb_Origin_i(Fl_Light_Button* o, void*) {
  glView->setorigin = o->value();
      if (glView->setorigin == false)
         glView->modelviewsetorigin((glView->w())/2, (glView->h())/2);
      else
         glView->cursor(FL_CURSOR_CROSS);
}
void FrameViewUI::cb_Origin(Fl_Light_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_Origin_i(o,v);
}

void FrameViewUI::cb_zoom_i(Fl_Value_Slider* o, void*) {
  glView->size[atframe] = ((Fl_Value_Slider *)o)->value();
      //printf("call callback for zoom slider\n");

      //glView->size[atframe] = pow(glView->size[atframe], 2);
      //commented out to revert to linear from exponential slider

      //printf("size in zoom widget = %g\n",glView->size[atframe]);
      glView->zoomfunc();
}
void FrameViewUI::cb_zoom(Fl_Value_Slider* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_zoom_i(o,v);
}

void FrameViewUI::cb_zoomadjuster_i(Fl_Adjuster* o, void*) {
  if ( Fl::event_key(FL_Left) || Fl::event_key(FL_Right) )
         return;

      Fl_Adjuster *a = (Fl_Adjuster*)o;
      glView->size[atframe] = a->value();
      //printf("in zoomadjuster: size[%d] = %g\n", atframe,
      //      glView->size[atframe]);
      // synchronize old zoomfunc
      ptrzoom->value(glView->size[atframe]);
      zoomdisplay->do_callback();
      glView->zoomfunc();
      glView->redraw();
}
void FrameViewUI::cb_zoomadjuster(Fl_Adjuster* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_zoomadjuster_i(o,v);
}

void FrameViewUI::cb_zoomdisplay_i(Fl_Box* o, void*) {
  //printf("atframe %d in zoomdisplay size relative to current "
      // "window = %g with size = %g and zoomfactor = %g\n", atframe,
      // glView->size[atframe] - glView->zoomfactor[atframe] + 1.00,
      // glView->size[atframe], glView->zoomfactor[atframe]);
      static char labbuf[100];

      //commented out in order to display size relative to current
      //window as opposed to relatice to original window 3/10/2008
      //sprintf(labbuf,"%6.2f", glView->size[atframe]);
      sprintf(labbuf,"%6.2f",
         glView->size[atframe] - glView->zoomfactor[atframe] + 1.00);
      o->label(labbuf);
}
void FrameViewUI::cb_zoomdisplay(Fl_Box* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_zoomdisplay_i(o,v);
}

void FrameViewUI::cb_GoTo_i(Fl_Value_Input* o, void*) {
  if (sListofCommands.empty())
         return;
      int gotoatframe = (int)(o->value());
      //printf("in GoTo with atframe = %d and goto value = %d\n",
      // atframe, gotoatframe);
      //fflush(stdout);
      if ( (gotoatframe > lastframe) || (gotoatframe < 1) ) {
         fl_beep();
         return;
         }
      //+++++comment out if frames in viewing not loading order +++++
      atframe = gotoatframe;
      fastforward  = false;
      fastprevious = false;

      drawFrameCommon(glView, 0, 1);
}
void FrameViewUI::cb_GoTo(Fl_Value_Input* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_GoTo_i(o,v);
}

void FrameViewUI::cb_Netdialog_i(Fl_Double_Window* o, void*) {
  o->hide();
      Controls->activate();
}
void FrameViewUI::cb_Netdialog(Fl_Double_Window* o, void* v) {
  ((FrameViewUI*)(o->user_data()))->cb_Netdialog_i(o,v);
}

void FrameViewUI::cb_Step_i(Fl_Button*, void*) {
  mmode = MM_STILL;
      //char debugmsg[300];
      //sprintf(debugmsg,"in step button: atframe %d mmode = %d, "
      // "will call nxtrfrm->do_callback()",atframe,mmode);
      //writetolog(debugmsg);
      Netdialog->hide();
}
void FrameViewUI::cb_Step(Fl_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_Step_i(o,v);
}

void FrameViewUI::cb_Movie_i(Fl_Button*, void*) {
  if (moreframes == false)
         //if there is no more connection to the science model
         // then there can be no movie
         return;
      Netdialog->hide();
      if (mmode == MM_STILL)
         fastforward = true;
      mmode = initmmode;
      //char debugmsg[300];
      //sprintf(debugmsg,"in movie button: atframe %d mmode = %d, "
      // "will call nxtrfrm->do_callback()",atframe,mmode);
      //writetolog(debugmsg);
      nxtfrm->do_callback();
}
void FrameViewUI::cb_Movie(Fl_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_Movie_i(o,v);
}

void FrameViewUI::cb_Interrupt_i(Fl_Button*, void*) {
  Netdialog->hide();
      interruptcns();
}
void FrameViewUI::cb_Interrupt(Fl_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_Interrupt_i(o,v);
}

void FrameViewUI::cb_Quit_i(Fl_Button*, void*) {
  if (!connectionclosed) {
         Netdialog->hide();
         closeconnection();
         quitpressed = true;
         }
      else {
         exit(0);
         };
}
void FrameViewUI::cb_Quit(Fl_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->parent()->user_data()))->cb_Quit_i(o,v);
}

void FrameViewUI::cb_CANCEL_i(Fl_Button*, void*) {
  minframeviewtimeprev->value(MINFRAMEVIEWTIMEPREV);
      minframeviewtimenext->value(MINFRAMEVIEWTIMENEXT);
      xposwindow->value(XPOSWINDOW);
      yposwindow->value(YPOSWINDOW);
      mainwindowwidthsize->value(MAINWINDOWWIDTHSIZE);

      //cout<<"cancel and restored INFRAMEVIEWTIMEPREV to "
      // <<(int)(minframeviewtimeprev->value())<<endl;
      //cout<<"cancel and restored INFRAMEVIEWTIMENEXT to "
      // <<(int)(minframeviewtimenext->value())<<endl;
      //cout<<"cancel and restored XPOSWINDOW to "
      // <<(int)(xposwindow->value())<<endl;
      //cout<<"cancel and restored YPOSWINDOW to "
      // <<(int)(yposwindow->value())<<endl;

      Settings->hide();
}
void FrameViewUI::cb_CANCEL(Fl_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->user_data()))->cb_CANCEL_i(o,v);
}

void FrameViewUI::cb_SAVE_i(Fl_Button*, void*) {
  MINFRAMEVIEWTIMEPREV = (double)(minframeviewtimeprev->value());
      MINFRAMEVIEWTIMENEXT = (double)(minframeviewtimenext->value());
      XPOSWINDOW = (int)(xposwindow->value());
      YPOSWINDOW = (int)(yposwindow->value());
      MAINWINDOWWIDTHSIZE = (int)(mainwindowwidthsize->value());

      char msglog[100];
      sprintf(msglog, "In save call back, preference file = %s\n",
         preffileinuse.c_str());
      writetolog(msglog);

      FILE *fp;
      fp = fopen(preffileinuse.c_str(),"w+");
      if (fp == NULL) {
         writetolog("Error in opening file .mfdrawrc");
         exit(1);
         }

      char *prefs = new char[500];
      sprintf(prefs, "MAXNUMFRAMES %d\nMINFRAMEVIEWTIMEPREV %.3f\n"
         "MINFRAMEVIEWTIMENEXT %.3f\nXPOSWINDOW %d\nYPOSWINDOW %d\n"
         "MAINWINDOWWIDTHSIZE %d",
         MAXNUMFRAMES,MINFRAMEVIEWTIMEPREV,MINFRAMEVIEWTIMENEXT,
         XPOSWINDOW,YPOSWINDOW,MAINWINDOWWIDTHSIZE);
      fprintf(fp, prefs);
      fclose(fp);
      Settings->hide();
      mainWindow->position(XPOSWINDOW,YPOSWINDOW);
      delete [] prefs;
}
void FrameViewUI::cb_SAVE(Fl_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->user_data()))->cb_SAVE_i(o,v);
}

void FrameViewUI::cb_OK_i(Fl_Button*, void*) {
  MINFRAMEVIEWTIMEPREV = (double)(minframeviewtimeprev->value());
      MINFRAMEVIEWTIMENEXT = (double)(minframeviewtimenext->value());
      XPOSWINDOW = (int)(xposwindow->value());
      YPOSWINDOW = (int)(yposwindow->value());
      MAINWINDOWWIDTHSIZE = (int)(mainwindowwidthsize->value());

      //cout<<"ok INFRAMEVIEWTIMEPREV = "
      // <<(int)(minframeviewtimeprev->value())<<endl;
      //cout<<"ok INFRAMEVIEWTIMENEXT = "
      // <<(int)(minframeviewtimenext->value())<<endl;
      //cout<<"ok XPOSWINDOW = "// <<(int)(xposwindow->value())<<endl;
      //cout<<"ok YPOSWINDOW = "<<(int)(yposwindow->value())<<endl;

      Settings->hide();
      mainWindow->position(XPOSWINDOW,YPOSWINDOW);
}
void FrameViewUI::cb_OK(Fl_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->user_data()))->cb_OK_i(o,v);
}

void FrameViewUI::cb_CONTINUE_i(Fl_Button*, void*) {
  ExitContinue->hide();
}
void FrameViewUI::cb_CONTINUE(Fl_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->user_data()))->cb_CONTINUE_i(o,v);
}

void FrameViewUI::cb_EXIT_i(Fl_Button*, void*) {
  exit(0);
}
void FrameViewUI::cb_EXIT(Fl_Button* o, void* v) {
  ((FrameViewUI*)(o->parent()->user_data()))->cb_EXIT_i(o,v);
}

FrameViewUI::FrameViewUI() {
  { mainWindow = new Fl_Double_Window(500, 525, "mfdraw");
    mainWindow->box(FL_UP_BOX);
    mainWindow->labelsize(12);
    mainWindow->callback((Fl_Callback*)cb_mainWindow, (void*)(this));
    { Controls = new Fl_Group(0, 0, 500, 25);
      { MenuFilebutton = new Fl_Menu_Button(1, 3, 50, 21, "&File");
        MenuFilebutton->labelsize(10);
        MenuFilebutton->menu(menu_MenuFilebutton);
      } // Fl_Menu_Button* MenuFilebutton
      { Fl_Button* o = Netbutton = new Fl_Button(54, 3, 41, 21, "&Net");
        Netbutton->labelsize(10);
        Netbutton->callback((Fl_Callback*)cb_Netbutton);
        Netbutton->hide();
        o->tooltip("Quit socket communication with "
      "science model or enter step, movie or interrupt mode");
      } // Fl_Button* Netbutton
      { Fl_Button* o = new Fl_Button(52, 3, 22, 21, "@|<");
        o->labelsize(10);
        o->callback((Fl_Callback*)cb_);
        o->tooltip("Display the first frame");
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(77, 3, 22, 21, "@<<");
        o->labelsize(10);
        o->callback((Fl_Callback*)cb_1);
        o->tooltip("Play frames as backward movie");
      } // Fl_Button* o
      { Fl_Button* o = prevfrm = new Fl_Button(101, 3, 22, 21, "@<-");
        prevfrm->labelsize(10);
        prevfrm->callback((Fl_Callback*)cb_prevfrm);
        o->tooltip("Previous frame");
        ptrprevfrm = o;
      } // Fl_Button* prevfrm
      { Fl_Button* o = new Fl_Button(124, 4, 22, 21, "@||");
        o->labelsize(10);
        o->callback((Fl_Callback*)cb_2);
        o->tooltip("Stop fast forward or fast previous");
      } // Fl_Button* o
      { Fl_Button* o = nxtfrm = new Fl_Button(150, 3, 22, 21, "@->");
        nxtfrm->labelsize(10);
        nxtfrm->callback((Fl_Callback*)cb_nxtfrm);
        o->tooltip("Advance frame");
        ptrnxtfrm = o;
      } // Fl_Button* nxtfrm
      { Fl_Button* o = new Fl_Button(173, 3, 22, 21, "@>>");
        o->labelsize(10);
        o->callback((Fl_Callback*)cb_3);
        o->tooltip("Fast forward frames");
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(196, 3, 22, 21, "@>|");
        o->labelsize(10);
        o->callback((Fl_Callback*)cb_4);
        o->tooltip("Display the last frame");
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(308, 3, 22, 21);
        o->image(image_fit);
        o->labelsize(10);
        o->callback((Fl_Callback*)cb_5);
        o->tooltip("Reset to initial view");
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(332, 3, 22, 21);
        o->image(image_background4);
        o->labelsize(10);
        o->callback((Fl_Callback*)cb_6);
        o->tooltip("Alternate white vs black background");
      } // Fl_Button* o
      { Fl_Light_Button* o = new Fl_Light_Button(331, 3, 55, 21, "&Origin");
        o->color((Fl_Color)48);
        o->selection_color((Fl_Color)71);
        o->labelsize(10);
        o->callback((Fl_Callback*)cb_Origin);
        o->hide();
        o->tooltip("Point and click to set new origin");
        ptrorigin = o;
      } // Fl_Light_Button* o
      { Fl_Value_Slider* o = zoom = new Fl_Value_Slider(271, 3, 229, 21, "Zoom");
        zoom->type(5);
        zoom->selection_color(FL_DARK_BLUE);
        zoom->labelfont(1);
        zoom->labelsize(10);
        zoom->minimum(0.5);
        zoom->maximum(100);
        zoom->step(0.02);
        zoom->value(1);
        zoom->textfont(1);
        zoom->callback((Fl_Callback*)cb_zoom);
        zoom->align(Fl_Align(FL_ALIGN_LEFT));
        zoom->hide();
        o->tooltip("Zoom in or out");
        ptrzoom = o;
      } // Fl_Value_Slider* zoom
      { zoomadjuster = new Fl_Adjuster(356, 3, 60, 21);
        zoomadjuster->minimum(0.25);
        zoomadjuster->maximum(100);
        zoomadjuster->step(0.005);
        zoomadjuster->value(1);
        zoomadjuster->callback((Fl_Callback*)cb_zoomadjuster, (void*)(&zoomdisplay));
        zoomadjuster->align(Fl_Align(FL_ALIGN_CENTER));
      } // Fl_Adjuster* zoomadjuster
      { zoomdisplay = new Fl_Box(418, 3, 55, 21, "1.0");
        zoomdisplay->box(FL_ENGRAVED_BOX);
        zoomdisplay->color((Fl_Color)215);
        zoomdisplay->callback((Fl_Callback*)cb_zoomdisplay);
        zoomdisplay->when(FL_WHEN_CHANGED);
      } // Fl_Box* zoomdisplay
      { Fl_Value_Input* o = new Fl_Value_Input(251, 3, 55, 21, "GoTo");
        o->box(FL_UP_BOX);
        o->labeltype(FL_ENGRAVED_LABEL);
        o->labelsize(10);
        o->textsize(12);
        o->callback((Fl_Callback*)cb_GoTo);
        o->when(FL_WHEN_ENTER_KEY_ALWAYS);
      } // Fl_Value_Input* o
      Controls->end();
    } // Fl_Group* Controls
    { Fl_Group* o = new Fl_Group(0, 25, 500, 500);
      { MainView = new Fl_Group(0, 25, 500, 500);
        { glView = new FrameView(0, 25, 500, 500);
          glView->box(FL_NO_BOX);
          glView->color(FL_BACKGROUND_COLOR);
          glView->selection_color(FL_BACKGROUND_COLOR);
          glView->labeltype(FL_NORMAL_LABEL);
          glView->labelfont(0);
          glView->labelsize(14);
          glView->labelcolor(FL_FOREGROUND_COLOR);
          glView->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
          glView->when(FL_WHEN_RELEASE);
        } // FrameView* glView
        MainView->end();
      } // Fl_Group* MainView
      o->end();
      Fl_Group::current()->resizable(o);
    } // Fl_Group* o
    //mainWindow->size_range(500,525);
    if (runmode == FILEMODE) Netbutton->deactivate();
    if (runmode == SOCKMODE) MenuFilebutton->mode(0,
      FL_MENU_INACTIVE);
    mainWindow->end();
  } // Fl_Double_Window* mainWindow
  { Fl_Double_Window* o = Netdialog = new Fl_Double_Window(245, 80);
    Netdialog->callback((Fl_Callback*)cb_Netdialog, (void*)(this));
    { Fl_Group* o = new Fl_Group(12, 20, 115, 55, "Mode of Operation");
      o->box(FL_BORDER_BOX);
      { Fl_Button* o = new Fl_Button(35, 24, 75, 20, "Step");
        o->callback((Fl_Callback*)cb_Step);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(34, 49, 75, 20, "Movie");
        o->callback((Fl_Callback*)cb_Movie);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(132, 20, 105, 55, "Action");
      o->box(FL_BORDER_BOX);
      { Fl_Button* o = new Fl_Button(147, 25, 75, 20, "Interrupt");
        o->callback((Fl_Callback*)cb_Interrupt);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(147, 50, 75, 20, "Quit");
        o->callback((Fl_Callback*)cb_Quit);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    ptrnetdialog = o;
    Netdialog->set_non_modal();
    Netdialog->end();
  } // Fl_Double_Window* Netdialog
  { Fl_Double_Window* o = Settings = new Fl_Double_Window(525, 505, "Settings");
    Settings->user_data((void*)(this));
    Settings->align(Fl_Align(FL_ALIGN_RIGHT));
    { minframeviewtimeprev = new Fl_Value_Input(296, 7, 49, 23, "Minimum previous frame viewing time (secs)");
      minframeviewtimeprev->maximum(10000);
      minframeviewtimeprev->step(0.001);
      minframeviewtimeprev->when(FL_WHEN_RELEASE_ALWAYS);
      minframeviewtimeprev->value(MINFRAMEVIEWTIMEPREV);
    } // Fl_Value_Input* minframeviewtimeprev
    { minframeviewtimenext = new Fl_Value_Input(296, 35, 49, 23, "Minimum forward frame viewing time (secs)");
      minframeviewtimenext->maximum(10000);
      minframeviewtimenext->step(0.001);
      minframeviewtimenext->when(FL_WHEN_RELEASE_ALWAYS);
      minframeviewtimenext->value(MINFRAMEVIEWTIMENEXT);
    } // Fl_Value_Input* minframeviewtimenext
    { xposwindow = new Fl_Value_Input(297, 64, 49, 23, "Initial Window  X Position");
      xposwindow->maximum(2000);
      xposwindow->step(1);
      xposwindow->when(FL_WHEN_RELEASE);
      xposwindow->value(XPOSWINDOW);
    } // Fl_Value_Input* xposwindow
    { yposwindow = new Fl_Value_Input(297, 92, 49, 23, "Initial Window  Y Position");
      yposwindow->maximum(2000);
      yposwindow->step(1);
      yposwindow->when(FL_WHEN_RELEASE);
      yposwindow->value(YPOSWINDOW);
    } // Fl_Value_Input* yposwindow
    { mainwindowwidthsize = new Fl_Value_Input(297, 121, 49, 23, "Initial Window  Width");
      mainwindowwidthsize->maximum(2000);
      mainwindowwidthsize->step(1);
      mainwindowwidthsize->when(FL_WHEN_RELEASE);
      mainwindowwidthsize->value(MAINWINDOWWIDTHSIZE);
    } // Fl_Value_Input* mainwindowwidthsize
    { Fl_Button* o = new Fl_Button(459, 470, 65, 25, "CANCEL");
      o->callback((Fl_Callback*)cb_CANCEL);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(329, 470, 65, 25, "SAVE");
      o->callback((Fl_Callback*)cb_SAVE);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(400, 470, 55, 25, "OK");
      o->callback((Fl_Callback*)cb_OK);
    } // Fl_Button* o
    ptrsettings = o;
    Settings->set_modal();
    Settings->end();
    Settings->resizable(Settings);
  } // Fl_Double_Window* Settings
  { Fl_Double_Window* o = ExitContinue = new Fl_Double_Window(145, 75);
    ExitContinue->user_data((void*)(this));
    ExitContinue->align(Fl_Align(FL_ALIGN_RIGHT));
    { Fl_Button* o = new Fl_Button(36, 44, 80, 25, "CONTINUE");
      o->callback((Fl_Callback*)cb_CONTINUE);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(36, 9, 80, 25, "EXIT");
      o->callback((Fl_Callback*)cb_EXIT);
    } // Fl_Button* o
    ptrexitcontinue = o;
    ExitContinue->set_modal();
    ExitContinue->end();
    ExitContinue->resizable(ExitContinue);
  } // Fl_Double_Window* ExitContinue
}

void FrameViewUI::show(int argc, char **argv) {
  if (runmode == SOCKMODE) {
        static char lbl[120];
        //display title on main window
        sprintf(lbl, "%s", header2.c_str());
        mainWindow->label(lbl);
        glView->init();
        }
  
  #if DEBUG & DBGSHOW
     writetolog("About to call mainWindow->show");
  #endif
  
     mainWindow->show(argc, argv);
  
  #if DEBUG & DBGSHOW
     sprintf(msglog,"size[1] = %g", pfvui->glView->size[1]);
     writetolog(msglog);
  #endif
  
     //overriding window manager for positioning
     mainWindow->position(XPOSWINDOW,YPOSWINDOW);
  
     if (runmode == FILEMODE) {
        //works in meta mode but not socket modes
        mainWindow->resize(XPOSWINDOW, YPOSWINDOW, MAINWINDOWWIDTHSIZE,
           MAINWINDOWWIDTHSIZE + 22);
        }
  
  #if DEBUG & DBGSHOW
     sprintf(msglog,"returned OK from mainWindow->resize, now "
        "size[1] = %g", pfvui->glView->size[1]);
     writetolog(msglog);
  #endif
}
